name: Build and Push Singularity Image

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: X86
    defaults:
      run:
        shell: bash
        working-directory: ./singularity
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      #- name: Build Singularity Image
      #  run: |
      #    sudo singularity build ciroh-ngen-singularity.sif singularity_ngen.def

      - name: Push Singularity Image to Library
        run: |
          singularity push -U /home/ubuntu/workspace/Ngen-Singularity/singularity/ciroh-ngen-singularity.sif library://awiciroh/ngiab/ciroh-ngen-singularity:latest