name: Build and Push Singularity Image

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: X86
    defaults:
      run:
        shell: bash
        working-directory: ./singularity
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Singularity Image
        run: |
          sudo singularity build ciroh-ngen-singularity.sif singularity_ngen.def

      - name: Test
        run: |
          rm -rf /home/ubuntu/workspace/AWI_09_004/partitions*.json
          rm -rf /home/ubuntu/workspace/AWI_09_004/*.csv
          rm -rf /home/ubuntu/workspace/AWI_09_004/*.parquet
          rm -rf /home/ubuntu/workspace/AWI_09_004/outputs/*
          singularity run --bind /home/ubuntu/workspace/AWI_09_004:/ngen/ngen/data ciroh-ngen-singularity.sif /ngen/ngen/data auto
        
      - name: Push Singularity Image to Library
        run: |
          singularity push -U ciroh-ngen-singularity.sif library://awiciroh/ngiab/ciroh-ngen-singularity:latest